services:
  frontend:
    image: manhwa-scanner-frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    network_mode: "host"
    env_file:
      - ./apps/frontend/.env.local
    environment:
      - BACKEND_URL=http://localhost:8000
  backend:
    image: manhwa-scanner-backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    network_mode: "host"
    env_file:
      - ./apps/backend/.env
  cron:
    image: manhwa-scanner-backend
    network_mode: "host"
    env_file:
      - ./apps/backend/.env
    environment:
      - ROLE=cron
    command: python -m app.main --port 3001
