module.exports = {
  apps: [
    {
      name: "manhwa-api",
      script: ".venv/bin/python",
      args: "app/main.py --port 3000",
      cwd: "/root/projects/manhwa-scanner/apps/backend",
      interpreter: "none",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 15,
      restart_delay: 3000,
      stop_exit_codes: [137],
      kill_timeout: 5000,
      env: {
        ROLE: "api",
        NODE_ENV: "production",
        PYTHONPATH: "/root/projects/manhwa-scanner/apps/backend",
      },
      error_file: "/root/.pm2/logs/manhwa-api-error.log",
      out_file: "/root/.pm2/logs/manhwa-api-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
    {
      name: "manhwa-cron",
      script: ".venv/bin/python",
      args: "app/main.py --port 3001",
      cwd: "/root/projects/manhwa-scanner/apps/backend",
      interpreter: "none",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "768M",
      min_uptime: "10s",
      max_restarts: 15,
      restart_delay: 5000,
      stop_exit_codes: [137],
      kill_timeout: 10000,
      env: {
        ROLE: "cron",
        NODE_ENV: "production",
        PYTHONPATH: "/root/projects/manhwa-scanner/apps/backend",
      },
      error_file: "/root/.pm2/logs/manhwa-cron-error.log",
      out_file: "/root/.pm2/logs/manhwa-cron-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
  ],
};
