name: Manga Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"  # setiap 5 menit (UTC)
  workflow_dispatch:

jobs:
  check-manga:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger time
        run: echo "Cron triggered at $(date -u)"

      - name: Call API Cron Endpoint
        run: |
          echo "Calling endpoint..."
          curl -X GET "${{ secrets.APP_URL }}/api/cron" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            --fail \
            --show-error \
            --location
          echo "Request success!"